language: java
sudo: false

jdk:
  - openjdk11

script:
  - jdk_switcher use openjdk11
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME
  - mvn clean package