### Basic scenario is:
###   1. create a couple of accounts
###   2. deposit some money to the accounts
###      using transactions with null senderId
###   3. create some transactions between accounts
###   4. check account balances

### Create new account

POST {{host}}:{{port}}/account

{
"name": "account_1",
"currency": "EUR"
}

### Get all account IDs

GET {{host}}:{{port}}/account

### Get account details

GET {{host}}:{{port}}/account/fd996fd9-0671-4ce3-ae8c-33d3ae6afb30

### Get account transactions

GET {{host}}:{{port}}/account/988c9501-ec76-446c-80a1-0c10871c9670/transactions

### Get transaction details

GET {{host}}:{{port}}/transaction/7caa0be0-1a43-4d26-bf44-295ec48a88f4

### Create new transaction

POST {{host}}:{{port}}/transaction

{
"senderId": "988c9501-ec76-446c-80a1-0c10871c9670",
"receiverId": "fd996fd9-0671-4ce3-ae8c-33d3ae6afb30",
"amountSent": "55.0",
"amountReceived": "55.0"
}

###